image: golang:1.23

stages:
  - build
  - test
  - deploy  

build-job:
  stage:
    build
  script:
    - go mod download
    - go build -o server ./cmd/main.go
  artifacts:
    paths:
      - server
      - static/
      - app.db

test-job:
  stage:
    test
  script:
    - echo "Testing Go...."

deploy-job:
  variables:
    DOCKER_TLS_CERTDIR: "" # /certs
    DOCKER_HOST: tcp://docker:2375
  image:
    docker:24.0.5  
  services:
    - docker:24.0.5-dind
  stage:
    deploy
  script:
    - docker login anniversary-card.cr.cloud.ru/anniversary-card -u $CLOUD_KEY_ID -p $CLOUD_KEY_SECRET
    - docker build -t anniversary-card.cr.cloud.ru/anniversary-card:latest .
    - docker push anniversary-card.cr.cloud.ru/anniversary-card:latest
